implement select
rhysd/tui-textarea pull request #45
Opened 2023-11-05 23:08 UTC by pm100

second go.

tested with all crossterm/ratatui samples. All work, including search, default select highlight color changed to be different from search highlight. Tested with hard and soft tabs, mask mode. plain ascii and complex chars

Notes. 
 - Changed `delete_str` core as `delete_str_internal` (user visible `delete_str` now calls `delete_str_internal`) to accept flags indicating whether or not to yank and / or delete. Since delete is optional maybe there is a better name. Why no delete sometimes?  ctrlc / copy needs to yank but not delete. Why no yank? If I select some text and then type it overwrites the selected text, so I need to delete, but should not yank (IMO)
 - The main change for users of the API is the inclusion of shift as a modifier in Input, hence the tweaks to a few samples
 - The other change is if they do not use `input` or `input_without_shortcuts` they must call `should_start_selection`. I was wondering about adding a sample for that. None of the current samples need it but I know that the project I work (gitui) on would
 - added ctrl-x cut and ctrl-c copy
 - as far as I can see termion does not propagate the shift key so select does not work with it

2023-11-06 01:49 UTC, pm100 commented
found a couple of bugs , back in a second

2023-11-06 02:18 UTC, pm100 commented
fixed

2023-11-06 02:29 UTC, pm100 commented
also tested on mac and linux. crossterm / ratatui

termion on linux, ignores select shift key so select does not work, but works fine otherwise (Ie I have not broken termion support)

One issue so far, putty (ssh client) connection to linux does not propagate all keys states, in particular it doesnt know about shift. 

tested on linux and windows using termwiz, works. Not exhaustively tested

2023-11-06 10:24 UTC, rhysd commented
Thank you. I'll review this today or tomorrow. And adding tests is really helpful.

2023-11-06 10:28 UTC, rhysd requested changes

2023-11-06 10:28 UTC, rhysd commented on src/textarea.rs
> +    /// and places it in the yank buffer
Can you add doc tests for each public APIs added in this PR so that users can understand the usage?

2023-11-06 10:28 UTC, rhysd commented on src/textarea.rs
> +        }
Can you make this hunk into one method like `LineHighligher::cursor_line` or `LineHighlighter::line_number`? I'd like to keep this method smaller and separate the logic for selection into the new method.

2023-11-06 10:29 UTC, rhysd commented
> One issue so far, putty (ssh client) connection to linux does not propagate all keys states, in particular it doesnt know about shift.

This sounds a problem of Putty and there seems nothing we can do.

2023-11-06 11:16 UTC, rhysd requested changes

2023-11-06 11:16 UTC, rhysd commented on tests/textarea.rs
> +    ] {
```rust
let (???, ???, ???, ???) = test;
```

Could you destructure the test case tuple at first in all tests? It is hard to understand what each elements represent without giving names to them.

2023-11-06 16:15 UTC, pm100 commented
> This sounds a problem of Putty and there seems nothing we can do.

I thought about for a few mins and this is a general issue with remote tings like SSH. They transmit the resulting ascii code not the actual key combinations.
- 'a' sends 0x61
- ctrl-a sends 0x01
- shift-a sends 0x41

But it was good to test just to make sure something not broken (same as termion)

2023-11-07 00:27 UTC, pm100 commented
i believe I have fixed all your issues. I also found a horrific set of bugs in multi byte char mode (japanese, etc). I did not realize that highlight boundaries are in bytes not chars. All fixed now

2023-11-10 12:09 UTC, rhysd approved these changes
This branch needs many refactorings but it is too time consuming for me to leave review comments on all places. And making the author fix all of them would be tough work. So I decided large refactoring after merging this PR.

For now, I merge this branch into main and then I'll add further changes tomorrow.

Thank you for adding this.

2023-11-10 12:10 UTC, merged

2023-11-21 04:59 UTC, pm100 commented
@rhysd I am working on another big PR (for word wrap). I am trying to merge the current head and am surprised by how much you changed the select PR. Its up to the caller to control it entirely. The automatic stop and start worked perfectly in the pure input case. Its not clear now what one should do to minimal sample for example to make select work.  I was not 100% happy with how it was controlled if you did not use the input function, but taking the auto select out entirely seems a bit harsh.

2023-11-21 07:25 UTC, rhysd commented
@pm100 You can take 100% control of selection by `TextArea::start_selection` and `TextArea::cancel_selection`. `TextArea::move_cursor` doesn't change the selection state. 

> to make select work

What does 'work' here mean?

>  I am working on another big PR

Did you see [this comment](https://github.com/rhysd/tui-textarea/issues/5#issuecomment-1814859687)? Refactorying of internal structure is necessary to avoid adhoc changes. Large PR is not acceptable since it is too hard to make it maintenable source.

2023-11-21 11:23 UTC, pm100 commented
@rhysd I misunderstood how you reworked the select PR. Ignore that comment, my bad

 you are going to really hate the word wrap PR.   But it adds huge benefit, please try it out before dismissing it. It was a lot of work !

2023-11-21 15:01 UTC, pm100 commented
I reread your select on and off logic, I prefer it. I was not 100% happy with it in the non 'input' case in my original code. Neat

________________________________
From: Linda_pp ***@***.***>
Sent: Monday, November 20, 2023 11:25:59 PM
To: rhysd/tui-textarea ***@***.***>
Cc: pm100 ***@***.***>; Mention ***@***.***>
Subject: Re: [rhysd/tui-textarea] implement select (PR #45)


@pm100<https://github.com/pm100> You can take 100% control of selection by TextArea::start_selection and TextArea::cancel_selection. TextArea::move_cursor doesn't change the selection state.

to make select work

What does 'work' here mean?

I am working on another big PR

Did you see this comment<https://github.com/rhysd/tui-textarea/issues/5#issuecomment-1814859687>? Refactorying of internal structure is necessary to avoid adhoc changes. Large PR is not acceptable since it is too hard to make it maintenable source.

—
Reply to this email directly, view it on GitHub<https://github.com/rhysd/tui-textarea/pull/45#issuecomment-1820369175>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AADXODYKLB73TF5MQJV75RDYFRJQPAVCNFSM6AAAAAA66VCBI6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRQGM3DSMJXGU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>